dist: trusty

os: linux

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  jobs:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

jobs:
  allow_failures:
    - php: nightly

install:
  - composer update --dev --prefer-source $PREFER_LOWEST

before_script:
  - sudo rabbitmqctl add_vhost testvhost
  - sudo rabbitmqctl add_user testuser testpassword
  - sudo rabbitmqctl set_permissions -p testvhost testuser ".*" ".*" ".*"

script:
  - ./vendor/bin/phpunit

services:
  - rabbitmq
