language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev --prefer-source
  - sudo rabbitmqctl add_vhost testvhost
  - sudo rabbitmqctl add_user testuser testpassword
  - sudo rabbitmqctl set_permissions -p testvhost testuser ".*" ".*" ".*"


script:
  - ./vendor/bin/phpuint

services:
  - rabbitmq
